version: "3"
codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "scripts/**/*"

comment:
  layout: "header, reach, diff, flags, files"
  behavior: default
  require_changes: no
