name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@14827154050720ad76378417d76718698539207e # master
        with:
          toolchain: stable
          components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@23b0d6598822003c091f930e169c84e16d470f1a # v2.7.3

      - name: Install dependencies
        uses: taiki-e/install-action@79796e6d1c86361bc482f3c7ef288597f742207b # v2.44.17
        with:
          tool: cargo-audit,cargo-tarpaulin

      - name: Run Cargo Clippy
        run: cargo clippy -- -D warnings

      - name: Run Cargo Audit
        run: cargo audit

      - name: Run Tests
        run: cargo test --test integration_test

      - name: Run Tarpaulin
        run: cargo tarpaulin --out xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1e68e0611db213e43899999a4e99f4d2f094593e # v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
          fail_ci_if_error: false
